-- Create events table
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  location TEXT,
  school_id UUID REFERENCES public.schools(id) DEFAULT 'd3b07384-d113-4956-a5ec-9af2c61146e5',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Policy for Public Select
CREATE POLICY "Events public select" ON public.events FOR SELECT USING (true);

-- Policy for Authenticated Manage (multi-tenant)
CREATE POLICY "Events multi-tenant manage" ON public.events FOR ALL TO authenticated
  USING (school_id = COALESCE((auth.jwt() -> 'user_metadata' ->> 'school_id')::uuid, 'd3b07384-d113-4956-a5ec-9af2c61146e5'))
  WITH CHECK (school_id = COALESCE((auth.jwt() -> 'user_metadata' ->> 'school_id')::uuid, 'd3b07384-d113-4956-a5ec-9af2c61146e5'));
