-- Create hero_slides table
CREATE TABLE IF NOT EXISTS public.hero_slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_url TEXT NOT NULL,
  school_id UUID REFERENCES public.schools(id) DEFAULT 'd3b07384-d113-4956-a5ec-9af2c61146e5',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.hero_slides ENABLE ROW LEVEL SECURITY;

-- Policy for Public Select
CREATE POLICY "Hero slides public select" ON public.hero_slides FOR SELECT USING (true);

-- Policy for Authenticated Manage (multi-tenant)
CREATE POLICY "Hero slides multi-tenant manage" ON public.hero_slides FOR ALL TO authenticated
  USING (school_id = COALESCE((auth.jwt() -> 'user_metadata' ->> 'school_id')::uuid, 'd3b07384-d113-4956-a5ec-9af2c61146e5'))
  WITH CHECK (school_id = COALESCE((auth.jwt() -> 'user_metadata' ->> 'school_id')::uuid, 'd3b07384-d113-4956-a5ec-9af2c61146e5'));
